# Generated by Django 6.1.1 on 2026-09-25 17:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('direction', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('999999999.99'))])),
                ('category', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True, default='', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-transaction_date', '-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='money_transaction_amount_min'), models.CheckConstraint(condition=models.Q(('amount__lte', Decimal('999999999.99'))), name='money_transaction_amount_max')],
            },
        ),
    ]
