# Generated by Django 6.1.1 on 2026-09-24 23:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('normal', 'Normal'), ('night', 'Night'), ('holiday', 'Holiday')], max_length=7)),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))])),
                ('note', models.TextField(blank=True, default='', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-work_date', '-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('worked_hours__gt', 0), ('worked_hours__lte', 24)), name='work_shift_worked_hours_range'), models.CheckConstraint(condition=models.Q(('overtime_hours__gte', 0), ('overtime_hours__lte', 24)), name='work_shift_overtime_hours_range'), models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0), ('hourly_rate__lte', 10000)), name='work_shift_hourly_rate_range')],
            },
        ),
    ]
