# Generated by Django 6.1.1 on 2026-09-26 17:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('habit_type', models.CharField(choices=[('check', 'Check'), ('quantity', 'Quantity'), ('abstinence', 'Abstinence'), ('chore', 'Scheduled chore')], default='check', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reminder_text', models.CharField(blank=True, default='', max_length=160)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('target_rule', models.CharField(blank=True, choices=[('at_least', 'At least'), ('at_most', 'At most'), ('range', 'Inclusive range')], default='', max_length=8)),
                ('lower_target', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999999.99'))])),
                ('upper_target', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999999.99'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('habit_type__in', ['check', 'quantity', 'abstinence', 'chore'])), name='habits_type_valid'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='habits_active_range'), models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('is_archived', False)), models.Q(('archived_at__isnull', False), ('is_archived', True)), _connector='OR'), name='habits_archive_state'), models.CheckConstraint(condition=models.Q(models.Q(('habit_type__in', ['check', 'abstinence', 'chore']), ('lower_target__isnull', True), ('target_rule', ''), ('unit', ''), ('upper_target__isnull', True)), models.Q(('habit_type', 'quantity'), models.Q(('unit', ''), _negated=True), models.Q(models.Q(('lower_target__isnull', False), ('target_rule', 'at_least'), ('upper_target__isnull', True)), models.Q(('lower_target__isnull', True), ('target_rule', 'at_most'), ('upper_target__isnull', False)), models.Q(('lower_target__isnull', False), ('target_rule', 'range'), ('upper_target__gte', models.F('lower_target')), ('upper_target__isnull', False)), _connector='OR')), _connector='OR'), name='habits_quantity_configuration'), models.CheckConstraint(condition=models.Q(('lower_target__isnull', True), models.Q(('lower_target__gte', 0), ('lower_target__lte', Decimal('999999999.99'))), _connector='OR'), name='habits_lower_target_bounds'), models.CheckConstraint(condition=models.Q(('upper_target__isnull', True), models.Q(('upper_target__gte', 0), ('upper_target__lte', Decimal('999999999.99'))), _connector='OR'), name='habits_upper_target_bounds')],
            },
        ),
    ]
