# Generated by Django 6.1.1 on 2026-09-26 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='anchor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='interval_n',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AddField(
            model_name='habit',
            name='interval_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=5),
        ),
        migrations.AddField(
            model_name='habit',
            name='recurrence_kind',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('interval', 'interval'), ('monthly_dates', 'monthly_dates'), ('monthly_ordinal_weekdays', 'monthly_ordinal_weekdays')], default='daily', max_length=24),
        ),
        migrations.CreateModel(
            name='HabitArchivePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_periods', to='habits.habit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='habits_archive_period_range'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('habit',), name='habits_one_open_archive')],
            },
        ),
        migrations.CreateModel(
            name='HabitPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pauses', to='habits.habit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='habits_pause_range')],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekday', 'Weekday'), ('month_day', 'Month date'), ('ordinal', 'Ordinal weekday')], max_length=12)),
                ('value', models.PositiveSmallIntegerField()),
                ('ordinal', models.SmallIntegerField(default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='habits.habit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('habit', 'kind', 'value', 'ordinal'), name='habits_component_unique'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'weekday'), ('ordinal', 0), ('value__gte', 0), ('value__lte', 6)), models.Q(('kind', 'month_day'), ('ordinal', 0), ('value__gte', 1), ('value__lte', 31)), models.Q(('kind', 'ordinal'), ('ordinal__in', [-1, 1, 2, 3, 4]), ('value__gte', 0), ('value__lte', 6)), _connector='OR'), name='habits_component_valid')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('kind', models.CharField(choices=[('addition', 'Addition'), ('exclusion', 'Exclusion')], max_length=9)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='habits.habit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('habit', 'day'), name='habits_exception_unique'), models.CheckConstraint(condition=models.Q(('kind__in', ['addition', 'exclusion'])), name='habits_exception_kind')],
            },
        ),
    ]
