# Generated by Django 6.1.1 on 2026-09-26 17:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_anchor_date_habit_interval_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField()),
                ('result', models.CharField(blank=True, choices=[('completed', 'Completed'), ('missed', 'Missed'), ('successful', 'Successful'), ('lapse', 'Lapse'), ('excused', 'Excused')], default='', max_length=10)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999999.99'))])),
                ('note', models.TextField(blank=True, default='', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('excuse_reason', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='habits.habit')),
            ],
            options={
                'ordering': ('-occurrence_date', '-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('habit', 'occurrence_date'), name='habits_occurrence_unique'), models.CheckConstraint(condition=models.Q(models.Q(('result__in', ['completed', 'missed', 'successful', 'lapse', 'excused']), ('value__isnull', True)), models.Q(('result', ''), ('value__gte', 0), ('value__isnull', False), ('value__lte', Decimal('999999999.99'))), _connector='OR'), name='habits_occurrence_evidence'), models.CheckConstraint(condition=models.Q(('result', 'excused'), ('excuse_reason', ''), _connector='OR'), name='habits_reason_only_excused')],
            },
        ),
    ]
