# Generated by Django 6.1.1 on 2026-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habitoccurrence'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('interval_n__gte', 1), ('interval_n__lte', 3650)), name='habits_interval_bounds'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence_kind', 'interval'), _negated=True), ('anchor_date__isnull', False), _connector='OR'), name='habits_interval_anchor'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_kind__in', ['daily', 'weekly', 'interval', 'monthly_dates', 'monthly_ordinal_weekdays'])), name='habits_recurrence_kind'),
        ),
    ]
